### PR TITLE
Add crypto adapters and domains attach support

### PR DESCRIPTION
**Pull request by bjzhangl**

### CODE REVIEW

**Comment by huoqifeng** [comment]
@bjzhangl may you please add snip code in sample for the new function as @jiangphcn mentioned, thanks!

**Comment by bjzhangl** [comment]
> @bjzhangl may you please add snip code in sample for the new function as @jiangphcn mentioned, thanks!

Sure.

**Comment by bjzhangl** [comment]
@huoqifeng @jiangphcn i add sample code, please help review.

**Review by huoqifeng — APPROVED** [review]
lgtm

**Comment by huoqifeng** [comment]
Thanks! @bjzhangl

**Pull request merged**
